### PR TITLE
Move data to a remote storage

### PR DESCRIPTION
**Pull request by rkargul**

### CODE REVIEW

**Comment by Iodine98** [comment]
@rkargul How can I check if the new feature works? Do I run `dvc repro` or smth?

**Comment by rkargul** [comment]
> 

Yes, if you run dvc repro, then a data folder with the datasets (three files) should be downloaded to your main folder

**Comment by Iodine98** [comment]
image

I ran `poetry update` followed by `dvc repro`, but I do not see the `data` folder anywhere when running `ls` inside the `model-training` root directory. @rkargul

**Review by Iodine98 — APPROVED** [review]
Running `poetry run dvc repro` downloads the files from remote storage:

image

Since it works on my PC, the feature has been demonstrated to work correctly.

**Comment by Iodine98** [comment]
@rkargul It still works, so you can merge it if you want:

image

I ran `poetry run dvc repro -f`, `-f` meaning force to force the reproduction of the pipeline after I had deleted the `./data` directory. Said directory appears after running the command, meaning that it does download from the remote storage.

**Pull request merged**
